project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!CountyOutputDashboard.qmd"
    - "!countySummary.qmd"

website:
  title: "District 1 Dashboards"
  navbar:
    background: primary
    search: false
    left:
      - text: "Home"
        href: index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
